### ISSUE TITLE
Incompatible with IntelliJ IDEA 2021.1

### ISSUE THREAD

**Issue by dimonchik0036** [google/ide-perf#36]
<img width="408" alt="изображение" src="https://user-images.githubusercontent.com/22503910/96828855-955a3680-1462-11eb-836a-e5312e45a811.png">

**Comment by gharrma** [comment]
Thanks, I'll update the until-build and release a version 1.0.1 soon!
(It appears I can just leave the until-build blank to ensure compatibility with all future IntelliJ versions.)

**Comment by gharrma** [comment]
Version 1.0.1 is submitted and pending review for the plugin repository.
In the meantime, feel free to download the release artifact manually [here](https://github.com/google/ide-perf/releases/tag/v1.0.1).

**Comment by gharrma** [comment]
Looks like 1.0.1 is available now; let me know if you run into any more issues using it with IJ 2021.1
