### ISSUE TITLE
About  USE

### ISSUE THREAD

**Issue by surengang** [google/ide-perf#52]
Could you provide some more detailed usage tutorials？

**Comment by gharrma** [comment]
Did you already read through the [User Guide](https://github.com/google/ide-perf/blob/master/docs/user-guide.md)? If so, let me know which parts could benefit from more detail. Thanks!

**Comment by surengang** [comment]
Sorry, I misunderstood the purpose of Tracer itself. It can only perform performance testing on IDE development environments

**Comment by gharrma** [comment]
Yes, that's right
